name: Auto Optimize
on:
  push:
    paths: ['*.webp']
jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install sharp
      - run: node auto-optimize.js
      - run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add *_google.png *_optimized.webp
          git commit -m 'Auto optimized images' || exit 0
          git push